version: '3.7'
services:
  communere:
    container_name: communere-service
    image: communere/communere-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:808
    environment:
      - "ASPNETCORE_URLS=http://+"
    #- Kestrel__Certificates__Default__Path=/app/Infrastructure/Certificate/cert-aspnetcore.pfx
    #- Kestrel__Certificates__Default__Password=SecretPassword

    restart: always
